language: ruby
cache: bundler

script: 'bundle exec rake test'

rvm:
  - 1.9.3
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
  - rbx-2.2
  - jruby-19mode
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2.2
    - rvm: jruby-19mode
    - rvm: jruby-head
